run-sensors:
	python3 -m flask_package.sensors

run-controller:
	python3 -m flask_package.controller

run-statistics:
	python3 -m grpc_package.statistics

run-dashboard:
	python3 -m grpc_package.dashboard $(port)


