run-client:
	python3 -m client.client

run-server:
	python3 -m server.server

run-dispatcher:
	cd /home/aldo-manzo/Scrivania/ACP/Esercitazioni/Esercitazione_gRPCJava/dispatcher/Dispatcher ; /usr/bin/env /usr/lib/jvm/java-21-openjdk-amd64/bin/java @/tmp/cp_855gn828mj8k97va8i0omzmm3.argfile dispatcher.Dispatcher $(port)