# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ordermanagement.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ordermanagement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15ordermanagement.proto\x12\tecommerce\"[\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x13\n\x0b\x64\x65stination\x18\x05 \x01(\t\"\x1b\n\rStringMessage\x12\n\n\x02id\x18\x01 \x01(\t2\x83\x01\n\x0fOrderManagement\x12\x38\n\x08\x61\x64\x64Order\x12\x10.ecommerce.Order\x1a\x18.ecommerce.StringMessage\"\x00\x12\x36\n\x08getOrder\x12\x18.ecommerce.StringMessage\x1a\x10.ecommerce.Orderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ordermanagement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=36
  _globals['_ORDER']._serialized_end=127
  _globals['_STRINGMESSAGE']._serialized_start=129
  _globals['_STRINGMESSAGE']._serialized_end=156
  _globals['_ORDERMANAGEMENT']._serialized_start=159
  _globals['_ORDERMANAGEMENT']._serialized_end=290
# @@protoc_insertion_point(module_scope)
