// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: magazzino.proto

package dispatcher;

public interface ItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dispatcher.Item)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 value = 1;</code>
   * @return The value.
   */
  long getValue();
}
