// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: magazzino.proto

package dispatcher;

public final class MagazzinoOuterClass {
  private MagazzinoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dispatcher_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dispatcher_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dispatcher_Item_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dispatcher_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017magazzino.proto\022\ndispatcher\"\007\n\005Empty\"\025" +
      "\n\004Item\022\r\n\005value\030\001 \001(\0032l\n\tMagazzino\022/\n\010de" +
      "posita\022\020.dispatcher.Item\032\021.dispatcher.Em" +
      "pty\022.\n\007preleva\022\021.dispatcher.Empty\032\020.disp" +
      "atcher.ItemB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dispatcher_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dispatcher_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dispatcher_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_dispatcher_Item_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dispatcher_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dispatcher_Item_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
