# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\"\x15\n\x04\x44\x61ta\x12\r\n\x05value\x18\x01 \x01(\x03\"\x07\n\x05\x45mpty\"\x17\n\x07\x41verage\x12\x0c\n\x04mean\x18\x01 \x01(\x02\"\x1d\n\x07Message\x12\x12\n\nstringmess\x18\x01 \x01(\t2l\n\x07Service\x12\x30\n\x0bstream_temp\x12\r.service.Data\x1a\x10.service.Message(\x01\x12/\n\x0bget_average\x12\x0e.service.Empty\x1a\x10.service.Averageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA']._serialized_start=26
  _globals['_DATA']._serialized_end=47
  _globals['_EMPTY']._serialized_start=49
  _globals['_EMPTY']._serialized_end=56
  _globals['_AVERAGE']._serialized_start=58
  _globals['_AVERAGE']._serialized_end=81
  _globals['_MESSAGE']._serialized_start=83
  _globals['_MESSAGE']._serialized_end=112
  _globals['_SERVICE']._serialized_start=114
  _globals['_SERVICE']._serialized_end=222
# @@protoc_insertion_point(module_scope)
