run-stats:
	python3 -m stats.stats

run-manager:
	cd /home/aldo-manzo/Scrivania/ACP/Esercitazioni/Esame_19_03_24/manager/Manager ; /usr/bin/env /usr/lib/jvm/java-21-openjdk-amd64/bin/java @/tmp/cp_ac6oxnf8sgnzkf8c5hnjr7rc2.argfile Manager 

run-client:
	cd /home/aldo-manzo/Scrivania/ACP/Esercitazioni/Esame_19_03_24/client/Client ; /usr/bin/env /usr/lib/jvm/java-21-openjdk-amd64/bin/java @/tmp/cp_cu3z6eucre61y7a3guiw4fndx.argfile Client $(req)