run-dashboard:
	python3 -m grpc_client.dashboard $(port)

run-statistics:
	python3 -m grpc_server.server 

run-controller:
	python3 -m flask_app.controller 

run-sensors:
	python3 -m flask_client.sensors 