run-statistics:
	python3 -m grpc_server.server

run-dashboard:
	python3 -m grpc_client.dashboard $(port)

run-sensors:
	python3 -m flask_client.sensors

run-controller:
	python3 -m flask_server.controller

