run-client:
	python3 -m client.client

run-server:
	python3 -m server.server

run-dispatcher:
	cd /home/aldo-manzo/Scrivania/ACP/Esercitazioni/Esercitazione_16_07_JMS_STOMP/dispatcher/dispatcher ; /usr/bin/env /usr/lib/jvm/java-21-openjdk-amd64/bin/java @/tmp/cp_37x29wv60g20udduo8usj22sk.argfile Dispatcher $(port)
