# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: magazzino.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'magazzino.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmagazzino.proto\x12\ndispatcher\"\x07\n\x05\x45mpty\"\x15\n\x04Item\x12\r\n\x05value\x18\x01 \x01(\x03\x32l\n\tMagazzino\x12/\n\x08\x64\x65posita\x12\x10.dispatcher.Item\x1a\x11.dispatcher.Empty\x12.\n\x07preleva\x12\x11.dispatcher.Empty\x1a\x10.dispatcher.ItemB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magazzino_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_EMPTY']._serialized_start=31
  _globals['_EMPTY']._serialized_end=38
  _globals['_ITEM']._serialized_start=40
  _globals['_ITEM']._serialized_end=61
  _globals['_MAGAZZINO']._serialized_start=63
  _globals['_MAGAZZINO']._serialized_end=171
# @@protoc_insertion_point(module_scope)
